# Switch to the Official Apache Spark image
FROM apache/spark:3.5.0

# Switch to root to install Python libs
USER root

# Install python dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Switch back to the default Apache Spark user (User ID 185)
USER 185